---
- hosts: all
  tasks:
 - authorized_key:
     user: charlie
     key: "{{ lookup('file', '/home/fiba/.ssh/id_rsa.pub') }}"
   - name: Install Nginx
     apt: pkg=nginx state=installed update_cache=true
